
language: python

python:
  - '3.9'

before_script:
  - cd pur_beurre_app
  - python -m venv env
  - source env/bin/activate
  - pip install -r requirements.txt --use-pep517 
  - python manage.py collectstatic

branches:
  only:
    - main

env: DJANGO_SETTINGS_MODULE=pur_beurre_app.settings.travis

services:
    - postgresql

script:
  - pytest
