
language: python

python:
  - '3.9'

before_script:
  - cd pur_beurre_app
  - python -m venv env
  - . venv/bin/activate
  - pip install -r requirements.txt

branches:
  only:
    - main

env: DJANGO_SETTINGS_MODULE="pur_beurre_app.settings.circle"

services:
    - postgresql

script:
  - pytest
