# language: python
# python:
#     - '3.11.2'

# before_script:
#     - pip install -r requirements.txt

# branches:
#   only:
#     - main

# env: DJANGO_SETTINGS_MODULE="pur_beurre_app.settings.circle"

# services:
#     - postgresql

# script:
#     - ./manage.py test

version: 3.4.5

jobs:
    build:
        docker:
            - image: cimg/python:3.11.2
        steps:
            - checkout
            - run:
                name: "Going at pur_beurre_app folder"
                command: cd pur_beurre_app
            - run:
                name: "Activate env virtual"
                command: |
                    python -m venv env
                    env\Scripts\Activate.ps1
                    pip install -r requirements.txt --use-pep517
            - run:
                name: "Running Tests"
                command: pytest
