language: python
python:
    - '3.11.2'

before_script:
    - pip install -r requirements.txt

branches:
  only:
    - main

env: DJANGO_SETTINGS_MODULE="pur_beurre_app.settings.circle"

services:
    - postgresql

script:
    - ./manage.py test

version: 3.4.5

jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    steps:
    - checkout
    - run: echo "A first hello" 